### ISSUE TITLE
What is the difference between stype='normal' and stype='stage'

### ISSUE THREAD

**Issue by ShoupingShan** [gasvn/Res2Net#11]
What is the difference between stype='normal' and stype='stage' in the Bottleneck

**Comment by gasvn** [comment]
Block with stage means that the this block is a down-sample block, where hierarchical connections are removed. There are only 3 blocks in a net that is `stage` block.

**Comment by ShoupingShan** [comment]
Thanks, I got it.

**Comment by cgebbe** [comment]
@gasvn : You say 

> There are only **3** blocks in a net that is stage block

However, according to https://github.com/Res2Net/Res2Net-PretrainedModels/blob/12dbee5abc92eaa270c0f972a398fa6a3bccd8b9/res2net.py#L134, the first block in every stage has stype='stage', so there are **4** blocks in total, or?

**Comment by gasvn** [comment]
> @gasvn : You say
> 
> > There are only **3** blocks in a net that is stage block
> 
> However, according to
> 
> https://github.com/Res2Net/Res2Net-PretrainedModels/blob/12dbee5abc92eaa270c0f972a398fa6a3bccd8b9/res2net.py#L134
> 
> , the first block in every stage has stype='stage', so there are **4** blocks in total, or?

This is a common design in resnet series. Resnet50  has [3, 4, 6, 3] blocks in stages. The overall network structure (channel number, stage number, block number in each stage) is mostly based on the resnet structure.  The hierarchical residual-like connections in Res2Net require the input and output features to have the same resolution. So when facing the downsampling, we remove the hierarchical connections in Res2Net block.  For res2net, strictly, [3,3,5,2] res2net blocks are used in stages.
