### ISSUE TITLE
Can you share codes of training and data augmentation?

### ISSUE THREAD

**Issue by c747903646** [gasvn/Res2Net#13]
Hi,

I hope to reproduce the same training result by runing program on my machine. Can you share codes of training and data augmentation that were used to get the result reported in this paper?

**Comment by gasvn** [comment]
Please refer to the offical pytorch training code: `https://github.com/pytorch/examples/tree/master/imagenet`

**Comment by c747903646** [comment]
These 3 py files didn't include all model reported in paper, such as Res2NeXt-29, 8c×25w×4s. Can I implement this model by adding codes as below? Is there anything else I should  do?

`def res2next29_8cx25wx4scale(pretrained=False, **kwargs):
    model = CifarRes2NeXt(Bottle2neckX, layers = [3, 3, 3], baseWidth = 25, cardinality=8, scale = 4, num_classes=100)
    return model`

**Comment by gasvn** [comment]
The cifar-res2next is based on cifar-resnext. The implemention of cifar-resnext is different from ImageNet-resnext, as described in the resnext paper. And you can replace the bottleneck block in cifar-resnext with the res2next block.

**Comment by c747903646** [comment]
OK, thanks！
