### ISSUE TITLE
Link 504 Gateway Time-out

### ISSUE THREAD

**Issue by Debrove** [gasvn/Res2Net#2]
Hi, when I download the pretrained models, it is found 504 Gateway Time-out. Also, the OneDrive Link can't be opened.

Thank you.

**Comment by gasvn** [comment]
The default download server is hosted on our school's server room. But there seem to have a connection issue in the school's server room. Sadly, now it’s summer vacation and no staff is on duty.
I have checked the OneDrive download link, it's working fine on some conditions (you need to cross the GFW if you are in mainland China). I am uploading models to Baidu Drive, and the Baidu Drive link will be soon available. 
Sorry for the inconvenience!

**Comment by gasvn** [comment]
The download link from baidu disk is now available:
https://pan.baidu.com/s/1BP7X222ZPqOndbojwOPjkw
password: vbix

I will fix the connection issue ASAP.

**Comment by Debrove** [comment]
Thank you very much.
