### ISSUE TITLE
load model issue

### ISSUE THREAD

**Issue by runzeer** [gasvn/Res2Net#5]
when I load the model in distributed mode,there exists the issue as follows. The first node cost the sum memory of the all memory.  But when I load the resnet models in the same way ,the issues disappear.Could you tell me the reason? Thanks a lot.

**Comment by gasvn** [comment]
Can you please show me your codes of loading ResNet and Res2Net? What's version of your torchvision and pytorch?

**Comment by mathpopo** [comment]
RuntimeError: Error(s) in loading state_dict for Res2Net:
	Unexpected key(s) in state_dict: "bn1.num_batches_tracked", "layer1.0.bn1.num_batches_tracked", "layer1.0.bns.0.num_batches_tracked", "layer1.0.bns.1.num_batches_tracked", "layer1.0.bns.2.num_batches_tracked", "layer1.0.bn3.num_batches_tracked", "layer1.0.downsample.1.num_batches_tracked", "layer1.1.bn1.num_batches_tracked", "layer1.1.bns.0.num_batches_tracked", "layer1.1.bns.1.num_batches_tracked", "layer1.1.bns.2.num_batches_tracked", "layer1.1.bn3.num_batches_tracked", "layer1.2.bn1.num_batches_tracked", "layer1.2.bns.0.num_batches_tracked", "layer1.2.bns.1.num_batches_tracked", "layer1.2.bns.2.num_batches_tracked", "layer1.2.bn3.num_batches_tracked", "layer2.0.bn1.num_batches_tracked", "layer2.0.bns.0.num_batches_tracked", "layer2.0.bns.1.num_batches_tracked", "layer2.0.bns.2.num_batches_tracked", "layer2.0.bn3.num_batches_tracked", "layer2.0.downsample.1.num_batches_tracked", "layer2.1.bn1.num_batches_tracked", "layer2.1.bns.0.num_batches_tracked", "layer2.1.bns.1.num_batches_tracked", "layer2.1.bns.2.num_batches_tracked", "layer2.1.bn3.num_batches_tracked", "layer2.2.bn1.num_batches_tracked", "layer2.2.bns.0.num_batches_tracked", "layer2.2.bns.1.num_batches_tracked", "layer2.2.bns.2.num_batches_tracked", "layer2.2.bn3.num_batches_tracked", "layer2.3.bn1.num_batches_tracked", "layer2.3.bns.0.num_batches_tracked", "layer2.3.bns.1.num_batches_tracked", "layer2.3.bns.2.num_batches_tracked", "layer2.3.bn3.num_batches_tracked", "layer3.0.bn1.num_batches_tracked", "layer3.0.bns.0.num_batches_tracked", "layer3.0.bns.1.num_batches_tracked", "layer3.0.bns.2.num_batches_tracked", "layer3.0.bn3.num_batches_tracked", "layer3.0.downsample.1.num_batches_tracked", "layer3.1.bn1.num_batches_tracked", "layer3.1.bns.0.num_batches_tracked", "layer3.1.bns.1.num_batches_tracked", "layer3.1.bns.2.num_batches_tracked", "layer3.1.bn3.num_batches_tracked", "layer3.2.bn1.num_batches_tracked", "layer3.2.bns.0.num_batches_tracked", "layer3.2.bns.1.num_batches_tracked", "layer3.2.bns.2.num_batches_tracked", "layer3.2.bn3.num_batches_tracked", "layer3.3.bn1.num_batches_tracked", "layer3.3.bns.0.num_batches_tracked", "layer3.3.bns.1.num_batches_tracked", "layer3.3.bns.2.num_batches_tracked", "layer3.3.bn3.num_batches_tracked", "layer3.4.bn1.num_batches_tracked", "layer3.4.bns.0.num_batches_tracked", "layer3.4.bns.1.num_batches_tracked", "layer3.4.bns.2.num_batches_tracked", "layer3.4.bn3.num_batches_tracked", "layer3.5.bn1.num_batches_tracked", "layer3.5.bns.0.num_batches_tracked", "layer3.5.bns.1.num_batches_tracked", "layer3.5.bns.2.num_batches_tracked", "layer3.5.bn3.num_batches_tracked", "layer3.6.bn1.num_batches_tracked", "layer3.6.bns.0.num_batches_tracked", "layer3.6.bns.1.num_batches_tracked", "layer3.6.bns.2.num_batches_tracked", "layer3.6.bn3.num_batches_tracked", "layer3.7.bn1.num_batches_tracked", "layer3.7.bns.0.num_batches_tracked", "layer3.7.bns.1.num_batches_tracked", "layer3.7.bns.2.num_batches_tracked", "layer3.7.bn3.num_batches_tracked", "layer3.8.bn1.num_batches_tracked", "layer3.8.bns.0.num_batches_tracked", "layer3.8.bns.1.num_batches_tracked", "layer3.8.bns.2.num_batches_tracked", "layer3.8.bn3.num_batches_tracked", "layer3.9.bn1.num_batches_tracked", "layer3.9.bns.0.num_batches_tracked", "layer3.9.bns.1.num_batches_tracked", "layer3.9.bns.2.num_batches_tracked", "layer3.9.bn3.num_batches_tracked", "layer3.10.bn1.num_batches_tracked", "layer3.10.bns.0.num_batches_tracked", "layer3.10.bns.1.num_batches_tracked", "layer3.10.bns.2.num_batches_tracked", "layer3.10.bn3.num_batches_tracked", "layer3.11.bn1.num_batches_tracked", "layer3.11.bns.0.num_batches_tracked", "layer3.11.bns.1.num_batches_tracked", "layer3.11.bns.2.num_batches_tracked", "layer3.11.bn3.num_batches_tracked", "layer3.12.bn1.num_batches_tracked", "layer3.12.bns.0.num_batches_tracked", "layer3.12.bns.1.num_batches_tracked", "layer3.12.bns.2.num_batches_tracked", "layer3.12.bn3.num_batches_tracked", "layer3.13.bn1.num_batches_tracked", "layer3.13.bns.0.num_batches_tracked", "layer3.13.bns.1.num_batches_tracked", "layer3.13.bns.2.num_batches_tracked", "layer3.13.bn3.num_batches_tracked", "layer3.14.bn1.num_batches_tracked", "layer3.14.bns.0.num_batches_tracked", "layer3.14.bns.1.num_batches_tracked", "layer3.14.bns.2.num_batches_tracked", "layer3.14.bn3.num_batches_tracked", "layer3.15.bn1.num_batches_tracked", "layer3.15.bns.0.num_batches_tracked", "layer3.15.bns.1.num_batches_tracked", "layer3.15.bns.2.num_batches_tracked", "layer3.15.bn3.num_batches_tracked", "layer3.16.bn1.num_batches_tracked", "layer3.16.bns.0.num_batches_tracked", "layer3.16.bns.1.num_batches_tracked", "layer3.16.bns.2.num_batches_tracked", "layer3.16.bn3.num_batches_tracked", "layer3.17.bn1.num_batches_tracked", "layer3.17.bns.0.num_batches_tracked", "layer3.17.bns.1.num_batches_tracked", "layer3.17.bns.2.num_batches_tracked", "layer3.17.bn3.num_batches_tracked", "layer3.18.bn1.num_batches_tracked", "layer3.18.bns.0.num_batches_tracked", "layer3.18.bns.1.num_batches_tracked", "layer3.18.bns.2.num_batches_tracked", "layer3.18.bn3.num_batches_tracked", "layer3.19.bn1.num_batches_tracked", "layer3.19.bns.0.num_batches_tracked", "layer3.19.bns.1.num_batches_tracked", "layer3.19.bns.2.num_batches_tracked", "layer3.19.bn3.num_batches_tracked", "layer3.20.bn1.num_batches_tracked", "layer3.20.bns.0.num_batches_tracked", "layer3.20.bns.1.num_batches_tracked", "layer3.20.bns.2.num_batches_tracked", "layer3.20.bn3.num_batches_tracked", "layer3.21.bn1.num_batches_tracked", "layer3.21.bns.0.num_batches_tracked", "layer3.21.bns.1.num_batches_tracked", "layer3.21.bns.2.num_batches_tracked", "layer3.21.bn3.num_batches_tracked", "layer3.22.bn1.num_batches_tracked", "layer3.22.bns.0.num_batches_tracked", "layer3.22.bns.1.num_batches_tracked", "layer3.22.bns.2.num_batches_tracked", "layer3.22.bn3.num_batches_tracked", "layer4.0.bn1.num_batches_tracked", "layer4.0.bns.0.num_batches_tracked", "layer4.0.bns.1.num_batches_tracked", "layer4.0.bns.2.num_batches_tracked", "layer4.0.bn3.num_batches_tracked", "layer4.0.downsample.1.num_batches_tracked", "layer4.1.bn1.num_batches_tracked", "layer4.1.bns.0.num_batches_tracked", "layer4.1.bns.1.num_batches_tracked", "layer4.1.bns.2.num_batches_tracked", "layer4.1.bn3.num_batches_tracked", "layer4.2.bn1.num_batches_tracked", "layer4.2.bns.0.num_batches_tracked", "layer4.2.bns.1.num_batches_tracked", "layer4.2.bns.2.num_batches_tracked", "layer4.2.bn3.num_batches_tracked".

**Comment by mathpopo** [comment]
cuda90                    1.0                  h6433d27_0    pytorch
pytorch                   1.0.0           py3.6_cuda9.0.176_cudnn7.4.1_1    <unknown>
torchvision               0.2.2                      py_3    pytorch

**Comment by gasvn** [comment]
Do you use the standard batchnorm?Or  have you changed the batchnorm to synchronous batchnorm?If the batchnorm you use doesn't have num_batches_tracked, you can just use strict = False when loading the model.

**Comment by gasvn** [comment]
> when I load the model in distributed mode,there exists the issue as follows. The first node cost the sum memory of the all memory. But when I load the resnet models in the same way ,the issues disappear.Could you tell me the reason? Thanks a lot.

The pretrained model is stored in GPU. You can use 
`checkpoint = torch.load(model_path, map_location=lambda storage, loc: storage)`  to avoid the memory usage in gpu by load pretrained weights into cpu.
