### ISSUE TITLE
Res2NeXt is better than Res2Net ?

### ISSUE THREAD

**Issue by RomanticWithoutStatus** [gasvn/Res2Net#6]
RT

**Comment by gasvn** [comment]
Small 3x3 convs in Res2Net module can be replaced with group conv. As we have observed, Res2NeXt still have a performance gain compared with Res2Net on the same scale.
Note that the ResNeXt in our baseline is a third part reimplementation(when we did this work at last year, the PyTorch model zoo didn't contain the ResNeXt), which has worse performance compared with the official reported results. We assume that with a better baseline of ResNeXt, the performance gap would be much larger.
Res2Net-50-26w-4s | 25.70M | 4.2 | 22.01 | 6.15
Res2NeXt-50            | 24.67M | 4.2 | 21.76 | 6.09
