### ISSUE TITLE
结构和论文不符

### ISSUE THREAD

**Issue by luuuyi** [gasvn/Res2Net#7]
作者你好，你的代码网络结构全部用了stype='stage'的连接，这种连接方式完全没体现出论文里面说的那种递进式连接关系，反而很像group卷积的意思，除了有一个用了pooling层而不是conv层，不知道你是出于什么考量。

**Comment by gasvn** [comment]
There are two types of commonly used bottleneck block with stride =2. One type is to set stride = 2 in 3x3 conv, another one is to set stride =2 in 1x1 conv. In our implementation, we follow the PyTorch official repo to use the first type of bottleneck block. The structure in our design requires the output of previous 3x3 conv has the same resolution with the input of next 3x3 conv within a Res2Net block. Thus, when stride = 2, we simply remove the connections among 3x3 convs. There are only three blocks in ResNet that has stride =2, so it may cause little difference in performance. Also, you can use the second type of bottleneck, and all blocks can be replaced with Res2Net block.

**Comment by lld533** [comment]
Hi,

A short question for you. May I know the downsample structure used to build a Res2NeXt model for CIFAR-100 in your paper?
A. 1x1 conv + bn
B. None
C. other structure. Please specify ____________

Many thanks:)

**Comment by gasvn** [comment]
Do you mean the short connection for downsample block? I use 1x1 conv + bn to downsample the short connection branch.
