### ISSUE TITLE
[state_dict] HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by frgfm** [gasvn/Res2Net#8]
Hey there,

Thanks a lot for your implementation! 
I tweaked it a bit for my personal need but it definitely helped me a lot.

Initially, when I checked, none of the links provided for [res2net](https://github.com/gasvn/Res2Net/blob/master/res2net.py) or [res2next](https://github.com/gasvn/Res2Net/blob/master/res2next.py) were working. So I used links to OneDrive you provided in the Readme. 

Unfortunately, OneDrive seems to regenerate download links regularly, meaning that I cannot use any static link for `wget`-like instructions. So I checked again and the links in your python files were working again.

Today I checked:
```
wget http://mc.nankai.edu.cn/projects/res2net/pretrainmodels/res2net50_26w_4s-06e79181.pth
```
and I received again the following error:
```
--2019-09-29 12:50:09--  http://mc.nankai.edu.cn/projects/res2net/pretrainmodels/res2net50_26w_4s-06e79181.pth
Resolving mc.nankai.edu.cn (mc.nankai.edu.cn)... 222.30.45.190
Connecting to mc.nankai.edu.cn (mc.nankai.edu.cn)|222.30.45.190|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-09-29 12:50:11 ERROR 403: Forbidden.
```

Am I doing anything wrong?
Could you let us know about the best way / fixed URLs to get the weights please?

Cheers

**Comment by frgfm** [comment]
I should specify that I live outside of China.
Accessing the URL in browser results in the university website requiring me to use the `Nankai University WebVPN system` to proceed.

**Comment by gasvn** [comment]
I am so sorry for the inconvenience. The server hosted in our school is not so stable. (Sadly, there is nothing I can do with it.) I was told that It will be will be back online within the next 2 to 3 weaks  for security reasons during the National holiday of China. I will notify you on this issue as soon as the download link is available.

There is a small trick for you to download the Onedrive link directly, which is changing the `ms`  in url with `ws`. (Don't forget to change the filename after downloading.) You can download it from Onedrive and move it to the default path of pytorch.

**Comment by zhouyuangan** [comment]
@gasvn Could you share pre-trained weight files on google driver? Thank u

**Comment by gasvn** [comment]
We provide onedirve and baidu drive download link for now. I will upload the pretrained model to google drive soon.

**Comment by zeakey** [comment]
Hi @zhouyuangan @frgfm , now all the pretrained models are hosted on the aliyun cloud storage.
Please checkout here <http://data.kaizhao.net/projects/res2net/index.html>.

I think this would be much more user-friendly than the ugly baidu yun.

For any other questions please feel free to contact me as well as Shanghua.
